version: '3.2'

services:
 app:
   container_name: bot
   build: .

  mongo:
    image: mongo:3.6
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=MySuperMegaPassword
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo:
